# Generated by Django 2.1 on 2018-08-29 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('riskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risktypes.RiskType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='numberfield',
            name='riskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risktypes.RiskType'),
        ),
        migrations.AddField(
            model_name='datefield',
            name='riskType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risktypes.RiskType'),
        ),
    ]
