# Generated by Django 2.1 on 2018-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='value',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='value',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
