# Generated by Django 2.1 on 2018-08-29 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0002_auto_20180829_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('riskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risktypes.RiskType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnumFieldValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField()),
                ('value', models.CharField(max_length=100)),
                ('enumField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risktypes.EnumField')),
            ],
        ),
    ]
