# Generated by Django 2.1 on 2018-08-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0003_enumfield_enumfieldvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datefield',
            old_name='riskType',
            new_name='risk_type',
        ),
        migrations.RenameField(
            model_name='enumfield',
            old_name='riskType',
            new_name='risk_type',
        ),
        migrations.RenameField(
            model_name='enumfieldvalue',
            old_name='enumField',
            new_name='enum_field',
        ),
        migrations.RenameField(
            model_name='numberfield',
            old_name='riskType',
            new_name='risk_type',
        ),
        migrations.RenameField(
            model_name='textfield',
            old_name='riskType',
            new_name='risk_type',
        ),
    ]
