# Generated by Django 2.1 on 2018-08-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0004_auto_20180829_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefield',
            name='value',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
