# Generated by Django 2.1 on 2018-08-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0005_auto_20180829_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumfieldvalue',
            name='key',
        ),
        migrations.AlterField(
            model_name='datefield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_fields', to='risktypes.RiskType'),
        ),
        migrations.AlterField(
            model_name='enumfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_fields', to='risktypes.RiskType'),
        ),
        migrations.AlterField(
            model_name='enumfieldvalue',
            name='enum_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum_field_values', to='risktypes.EnumField'),
        ),
        migrations.AlterField(
            model_name='numberfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='number_fields', to='risktypes.RiskType'),
        ),
        migrations.AlterField(
            model_name='textfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_fields', to='risktypes.RiskType'),
        ),
    ]
