# Generated by Django 2.1 on 2018-09-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0006_auto_20180830_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datefield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='enumfieldvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='numberfield',
            name='value',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='value',
        ),
    ]
