# Generated by Django 2.1 on 2018-09-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risktypes', '0007_auto_20180904_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumfieldvalue',
            name='value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
